{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autenticacion-ms.serviceAccountName" . }}
  namespace: {{ include "autenticacion-ms.namespace" . }}
  labels:
    {{- include "autenticacion-ms.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}

