scalar DateTime
scalar UUID

type DetallePrestamo {
  idDetalle: UUID!
  idPrestamo: UUID!
  idEjemplar: UUID!
  fechaDevolucion: DateTime
  estado: String!
}

type Prestamo {
  idPrestamo: UUID!
  idUsuario: UUID!
  fechaPrestamo: DateTime!
  fechaLimite: DateTime!
  estado: String!
  fechaCreacion: DateTime!
  actualizadoEn: DateTime!
  detalles: [DetallePrestamo!]!
}

type Query {
  prestamo(id: UUID!): Prestamo!
  prestamosPorUsuario(idUsuario: UUID!): [Prestamo!]!
}

type Mutation {
  crearPrestamo(idUsuario: UUID!, idsEjemplares: [UUID!]!, fechaLimite: DateTime!): Prestamo!
  devolverEjemplar(idDetalle: UUID!): DetallePrestamo!
}
