{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "multas-ms.serviceAccountName" . }}
  namespace: {{ include "multas-ms.namespace" . }}
automountServiceAccountToken: false
{{- end }}
