from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.models.loan import Loan, LoanDetail


class LoanRepository(Protocol):
    def create(self, user_id: UUID, due_date: datetime, copy_ids: list[UUID]) -> Loan: ...

    def find_by_id(self, loan_id: UUID) -> Loan: ...

    def find_by_user(self, user_id: UUID) -> list[Loan]: ...

    def find_detail_by_id(self, detail_id: UUID) -> LoanDetail: ...

    def return_detail(self, detail_id: UUID, return_date: datetime) -> LoanDetail: ...

    def find_overdue(self, current_time: datetime) -> list[Loan]: ...

    def mark_overdue(self, loan_id: UUID) -> Loan: ...


class CatalogClient(Protocol):
    def update_copy_status(self, copy_id: UUID, status: str) -> None: ...


class FineClient(Protocol):
    def create_fine(self, loan: Loan, days_overdue: int) -> None: ...
