{{- $namespace := include "sa-platform.namespace" . }}
{{- range $name := list "api-gateway" "autenticacion-ms" "catalogo-ms" "prestamos-ms" "multas-ms" "cronjob1" "cronjob2" "summary-consumer" "p9-rollouts" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/part-of: sa-platform-p9
    app.kubernetes.io/managed-by: gitops
automountServiceAccountToken: false
{{- if not (eq $name "p9-rollouts") }}
---
{{- end }}
{{- end }}
