apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}
  namespace: {{ include "api-gateway.namespace" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  nginx.conf: |
    pid /tmp/nginx.pid;

    events {}

    http {
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path /tmp/proxy_temp;
      fastcgi_temp_path /tmp/fastcgi_temp;
      uwsgi_temp_path /tmp/uwsgi_temp;
      scgi_temp_path /tmp/scgi_temp;

      server {
        listen {{ .Values.service.port }};
        server_name _;
        default_type application/json;
        client_max_body_size 1m;
        add_header X-Platform-Version {{ .Values.platformVersion | quote }} always;
        resolver {{ .Values.upstreams.resolver }} valid=10s ipv6=off;

        set $autenticacion_upstream "{{ .Values.upstreams.autenticacion }}";
        set $catalogo_upstream "{{ .Values.upstreams.catalogo }}";
        set $prestamos_upstream "{{ .Values.upstreams.prestamos }}";
        set $multas_upstream "{{ .Values.upstreams.multas }}";

        location = /health {
          return 200 '{"status":"ok","servicio":"api-gateway"}';
        }
        location = /health/auth {
          proxy_pass http://$autenticacion_upstream/health;
        }
        location = /health/catalogo {
          proxy_pass http://$catalogo_upstream/health;
        }
        location = /health/prestamos {
          proxy_pass http://$prestamos_upstream/health;
        }
        location = /health/multas {
          proxy_pass http://$multas_upstream/health;
        }
        location ^~ /api/v1/auth/ {
          proxy_pass http://$autenticacion_upstream;
        }
        location ^~ /api/v1/ejemplares/ {
          proxy_pass http://$catalogo_upstream;
        }
        location ^~ /api/v1/prestamos/ {
          proxy_pass http://$prestamos_upstream;
        }
        location = /api/v1/multas {
          proxy_pass http://$multas_upstream;
        }
        location ^~ /api/v1/multas/ {
          proxy_pass http://$multas_upstream;
        }
        location ~ ^/api/v1/usuarios/[^/]+/multas$ {
          proxy_pass http://$multas_upstream;
        }
        location = /catalogo/graphql {
          proxy_pass http://$catalogo_upstream/graphql;
        }
        location = /prestamos/graphql {
          proxy_pass http://$prestamos_upstream/graphql;
        }
        location / {
          return 404 '{"error":"RUTA_NO_ENCONTRADA","mensaje":"La ruta no existe en el API Gateway"}';
        }
      }
    }
