{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prestamos-ms.serviceAccountName" . }}
  namespace: {{ include "prestamos-ms.namespace" . }}
  labels: {{- include "prestamos-ms.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
