apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autenticacion-ms.fullname" . }}
  namespace: {{ include "autenticacion-ms.namespace" . }}
  labels:
    {{- include "autenticacion-ms.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.service.port | quote }}
  JWT_DURATION_MINUTES: {{ .Values.config.jwtDurationMinutes | quote }}
  LOG_LEVEL: {{ default "info" .Values.config.logLevel | quote }}

