type Categoria {
  id_categoria: ID!
  nombre: String!
  descripcion: String
}

type Autor {
  id_autor: ID!
  nombre: String!
  apellido: String!
}

type Ejemplar {
  id_ejemplar: ID!
  id_libro: ID!
  codigo_inventario: String!
  estado: String!
  fecha_creacion: DateTime!
  actualizado_en: DateTime!
}

type Libro {
  id_libro: ID!
  titulo: String!
  editorial: String!
  anio_publicacion: Int!
  activo: Boolean!
  categoria: Categoria!
  autores: [Autor!]!
  ejemplares: [Ejemplar!]!
}

type Query {
  categorias: [Categoria!]!
  autores: [Autor!]!
  libros: [Libro!]!
  libro(id: ID!): Libro
}

type Mutation {
  crearCategoria(nombre: String!, descripcion: String): Categoria
  crearAutor(nombre: String!, apellido: String!): Autor
  crearLibro(titulo: String!, editorial: String!, anio_publicacion: Int!, id_categoria: ID!, ids_autores: [ID!]!): Libro
  crearEjemplar(id_libro: ID!, codigo_inventario: String!): Ejemplar
  actualizarEstadoEjemplar(id: ID!, estado: String!): Ejemplar
}

scalar DateTime
