FROM nginxinc/nginx-unprivileged:1.27-alpine AS validation

COPY nginx.conf /etc/nginx/nginx.conf
RUN nginx -t

FROM nginxinc/nginx-unprivileged:1.27-alpine AS production

COPY --from=validation /etc/nginx/nginx.conf /etc/nginx/nginx.conf

USER nginx
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
