pid /tmp/nginx.pid;

events {}

http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    server {
        listen 8080;
        server_name _;

        default_type application/json;
        client_max_body_size 1m;
        resolver kube-dns.kube-system.svc.cluster.local valid=10s ipv6=off;

        set $autenticacion_upstream "autenticacion-ms:8081";
        set $catalogo_upstream "catalogo-ms:8082";
        set $prestamos_upstream "prestamos-ms:8083";
        set $multas_upstream "multas-ms:8084";

        location = /health {
            return 200 '{"status":"ok","servicio":"api-gateway"}';
        }

        location = /health/auth {
            proxy_pass http://$autenticacion_upstream/health;
        }

        location = /health/catalogo {
            proxy_pass http://$catalogo_upstream/health;
        }

        location = /health/prestamos {
            proxy_pass http://$prestamos_upstream/health;
        }

        location = /health/multas {
            proxy_pass http://$multas_upstream/health;
        }

        location ^~ /api/v1/auth/ {
            proxy_pass http://$autenticacion_upstream;
        }

        location ^~ /api/v1/ejemplares/ {
            proxy_pass http://$catalogo_upstream;
        }

        location ^~ /api/v1/prestamos/ {
            proxy_pass http://$prestamos_upstream;
        }

        location = /api/v1/multas {
            proxy_pass http://$multas_upstream;
        }

        location ^~ /api/v1/multas/ {
            proxy_pass http://$multas_upstream;
        }

        location ~ ^/api/v1/usuarios/[^/]+/multas$ {
            proxy_pass http://$multas_upstream;
        }

        location = /catalogo/graphql {
            proxy_pass http://$catalogo_upstream/graphql;
        }

        location = /prestamos/graphql {
            proxy_pass http://$prestamos_upstream/graphql;
        }

        location / {
            return 404 '{"error":"RUTA_NO_ENCONTRADA","mensaje":"La ruta no existe en el API Gateway"}';
        }
    }
}
