apiVersion: v1
kind: Service
metadata:
  name: {{ include "multas-ms.fullname" . }}
  namespace: {{ include "multas-ms.namespace" . }}
  labels: {{- include "multas-ms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "multas-ms.selectorLabels" . | nindent 4 }}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}
