{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-gateway-access
  namespace: {{ include "sa-platform.namespace" . }}
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicies.ingressControllerNamespace | quote }}
          podSelector:
            matchLabels:
              app.kubernetes.io/component: controller
      ports:
        - {protocol: TCP, port: 8080}
  egress:
    - to:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: [autenticacion-ms, catalogo-ms, prestamos-ms, multas-ms]
              - key: app.kubernetes.io/instance
                operator: In
                values: [{{ .Release.Name }}]
      ports:
        - {protocol: TCP, port: 8081}
        - {protocol: TCP, port: 8082}
        - {protocol: TCP, port: 8083}
        - {protocol: TCP, port: 8084}
{{- end }}
