{{- if .Values.externalSecrets.enabled }}
{{- $namespace := .Values.global.namespace }}
{{- $store := .Values.externalSecrets.secretStoreName }}
{{- $interval := .Values.externalSecrets.refreshInterval }}
{{- range $item := list
  (dict "name" "auth-postgresql-credentials")
  (dict "name" "catalog-postgresql-credentials")
  (dict "name" "loans-postgresql-credentials")
  (dict "name" "fines-postgresql-credentials")
  (dict "name" "cronjobs-postgresql-credentials")
  (dict "name" "rabbitmq-credentials")
  (dict "name" "jwt-credentials")
}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $item.name }}
  namespace: {{ $namespace }}
spec:
  refreshInterval: {{ $interval }}
  secretStoreRef:
    name: {{ $store }}
    kind: ClusterSecretStore
  target:
    name: {{ $item.name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: p8-{{ $item.name }}
---
{{- end }}
{{- end }}
