replicaCount: 2
fullnameOverride: ""
image: {repository: ghcr.io/izabel05/sa-multas-ms, tag: "v1.2.2", pullPolicy: IfNotPresent}
serviceAccount: {create: true, name: ""}
service: {type: ClusterIP, port: 8084}
config: {logLevel: info, dailyRate: "5.00"}
database: {secretName: fines-postgresql-credentials, secretKey: database-url}
rabbitmq: {secretName: rabbitmq-credentials, secretKey: amqp-url, queue: multa.requerida}
resources:
  requests: {cpu: 50m, memory: 96Mi}
  limits: {cpu: 300m, memory: 192Mi}
autoscaling: {enabled: true, minReplicas: 2, maxReplicas: 5, targetCPUUtilizationPercentage: 70}
podDisruptionBudget: {enabled: true, minAvailable: 1}
probes:
  startup: {failureThreshold: 30, periodSeconds: 2}
  readiness: {initialDelaySeconds: 2, periodSeconds: 5}
  liveness: {initialDelaySeconds: 5, periodSeconds: 10}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  seccompProfile: {type: RuntimeDefault}
securityContext: {allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, capabilities: {drop: [ALL]}}
